SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

USE `map_places_db`;

INSERT INTO `types` (`id`, `name`, `letter`) VALUES
(1, 'Restaurants', 'R'),
(2, 'Bars', 'B'),
(3, 'Museums', 'M');

INSERT INTO `markers` (`id`, `name`, `address`, `lat`, `lng`, `type`) VALUES
(1, 'Pan Africa Market', '1521 1st Ave, Seattle, WA', '47.608940', '-122.340141', 1),
(2, 'Buddha Thai & Bar', '2222 2nd Ave, Seattle, WA', '47.613590', '-122.344391', 2),
(3, 'The Melting Pot', '14 Mercer St, Seattle, WA', '47.624561', '-122.356445', 3),
(4, 'Ipanema Grill', '1225 1st Ave, Seattle, WA', '47.606365', '-122.337654', 1),
(5, 'Sake House', '2230 1st Ave, Seattle, WA', '47.612823', '-122.345673', 2),
(6, 'Crab Pot', '1301 Alaskan Way, Seattle, WA', '47.605961', '-122.340363', 1),
(7, 'Mama''s Mexican Kitchen', '2234 2nd Ave, Seattle, WA', '47.613976', '-122.345467', 3),
(8, 'Wingdome', '1416 E Olive Way, Seattle, WA', '47.617214', '-122.326584', 2),
(9, 'Piroshky Piroshky', '1908 Pike pl, Seattle, WA', '47.610126', '-122.342834', 3);

INSERT INTO `contents` (`id`, `email`, `url`, `phone`, `text`, `marker`) VALUES
(1, 'user@domain.com', 'www.domain.com', '2310456789', 'To be or not to be - that is the question: Whether ''tis nobler in the mind to suffer. The slings and arrows of outrageous fortune, Or to take arms against a sea of troubles. And, by opposing, end them. To die, to sleep. No more - and by a sleep to say we end. The heartache and the thousand natural shocks. That flesh is heir to - tis a consummation. Devoutly to be wished. To die, to sleep. To sleep, perchance to dream. Ay, there''s the rub, For in that sleep of death what dreams may come, When we have shuffled off this mortal coil, Must give us pause. There''s the respect. That makes calamity of so long life. For who would bear the whips and scorns of time, Th’ oppressor''s wrong, the proud man''s contumely, The pangs of despised love, the law''s delay, The insolence of office, and the spurns That patient merit of th’ unworthy takes, When he himself might his quietus make. With a bare bodkin? Who would fardels bear, To grunt and sweat under a weary life, But that the dread of something after death, The undiscovered country from whose bourn. No traveler returns, puzzles the will. And makes us rather bear those ills we have. Than fly to others that we know not of? Thus conscience does make cowards of us all, And thus the native hue of resolution. Is sicklied o''er with the pale cast of thought, And enterprises of great pitch and moment. With this regard their currents turn awry, And lose the name of action. - Soft you now!. The fair Ophelia! Nymph, in thy orisons. Be all my sins remembered.', 1),
(2, 'user@domain.com', 'www.domain.com', '2310456789', 'To be or not to be - that is the question: Whether ''tis nobler in the mind to suffer. The slings and arrows of outrageous fortune, Or to take arms against a sea of troubles. And, by opposing, end them. To die, to sleep. No more - and by a sleep to say we end. The heartache and the thousand natural shocks. That flesh is heir to - tis a consummation. Devoutly to be wished. To die, to sleep. To sleep, perchance to dream. Ay, there''s the rub, For in that sleep of death what dreams may come, When we have shuffled off this mortal coil, Must give us pause. There''s the respect. That makes calamity of so long life. For who would bear the whips and scorns of time, Th’ oppressor''s wrong, the proud man''s contumely, The pangs of despised love, the law''s delay, The insolence of office, and the spurns That patient merit of th’ unworthy takes, When he himself might his quietus make. With a bare bodkin? Who would fardels bear, To grunt and sweat under a weary life, But that the dread of something after death, The undiscovered country from whose bourn. No traveler returns, puzzles the will. And makes us rather bear those ills we have. Than fly to others that we know not of? Thus conscience does make cowards of us all, And thus the native hue of resolution. Is sicklied o''er with the pale cast of thought, And enterprises of great pitch and moment. With this regard their currents turn awry, And lose the name of action. - Soft you now!. The fair Ophelia! Nymph, in thy orisons. Be all my sins remembered.', 2),
(3, 'user@domain.com', 'www.domain.com', '2310456789', 'To be or not to be - that is the question: Whether ''tis nobler in the mind to suffer. The slings and arrows of outrageous fortune, Or to take arms against a sea of troubles. And, by opposing, end them. To die, to sleep. No more - and by a sleep to say we end. The heartache and the thousand natural shocks. That flesh is heir to - tis a consummation. Devoutly to be wished. To die, to sleep. To sleep, perchance to dream. Ay, there''s the rub, For in that sleep of death what dreams may come, When we have shuffled off this mortal coil, Must give us pause. There''s the respect. That makes calamity of so long life. For who would bear the whips and scorns of time, Th’ oppressor''s wrong, the proud man''s contumely, The pangs of despised love, the law''s delay, The insolence of office, and the spurns That patient merit of th’ unworthy takes, When he himself might his quietus make. With a bare bodkin? Who would fardels bear, To grunt and sweat under a weary life, But that the dread of something after death, The undiscovered country from whose bourn. No traveler returns, puzzles the will. And makes us rather bear those ills we have. Than fly to others that we know not of? Thus conscience does make cowards of us all, And thus the native hue of resolution. Is sicklied o''er with the pale cast of thought, And enterprises of great pitch and moment. With this regard their currents turn awry, And lose the name of action. - Soft you now!. The fair Ophelia! Nymph, in thy orisons. Be all my sins remembered.', 3),
(4, 'user@domain.com', 'www.domain.com', '2310456789', 'To be or not to be - that is the question: Whether ''tis nobler in the mind to suffer. The slings and arrows of outrageous fortune, Or to take arms against a sea of troubles. And, by opposing, end them. To die, to sleep. No more - and by a sleep to say we end. The heartache and the thousand natural shocks. That flesh is heir to - tis a consummation. Devoutly to be wished. To die, to sleep. To sleep, perchance to dream. Ay, there''s the rub, For in that sleep of death what dreams may come, When we have shuffled off this mortal coil, Must give us pause. There''s the respect. That makes calamity of so long life. For who would bear the whips and scorns of time, Th’ oppressor''s wrong, the proud man''s contumely, The pangs of despised love, the law''s delay, The insolence of office, and the spurns That patient merit of th’ unworthy takes, When he himself might his quietus make. With a bare bodkin? Who would fardels bear, To grunt and sweat under a weary life, But that the dread of something after death, The undiscovered country from whose bourn. No traveler returns, puzzles the will. And makes us rather bear those ills we have. Than fly to others that we know not of? Thus conscience does make cowards of us all, And thus the native hue of resolution. Is sicklied o''er with the pale cast of thought, And enterprises of great pitch and moment. With this regard their currents turn awry, And lose the name of action. - Soft you now!. The fair Ophelia! Nymph, in thy orisons. Be all my sins remembered.', 4),
(5, 'user@domain.com', 'www.domain.com', '2310456789', 'To be or not to be - that is the question: Whether ''tis nobler in the mind to suffer. The slings and arrows of outrageous fortune, Or to take arms against a sea of troubles. And, by opposing, end them. To die, to sleep. No more - and by a sleep to say we end. The heartache and the thousand natural shocks. That flesh is heir to - tis a consummation. Devoutly to be wished. To die, to sleep. To sleep, perchance to dream. Ay, there''s the rub, For in that sleep of death what dreams may come, When we have shuffled off this mortal coil, Must give us pause. There''s the respect. That makes calamity of so long life. For who would bear the whips and scorns of time, Th’ oppressor''s wrong, the proud man''s contumely, The pangs of despised love, the law''s delay, The insolence of office, and the spurns That patient merit of th’ unworthy takes, When he himself might his quietus make. With a bare bodkin? Who would fardels bear, To grunt and sweat under a weary life, But that the dread of something after death, The undiscovered country from whose bourn. No traveler returns, puzzles the will. And makes us rather bear those ills we have. Than fly to others that we know not of? Thus conscience does make cowards of us all, And thus the native hue of resolution. Is sicklied o''er with the pale cast of thought, And enterprises of great pitch and moment. With this regard their currents turn awry, And lose the name of action. - Soft you now!. The fair Ophelia! Nymph, in thy orisons. Be all my sins remembered.', 5),
(6, 'user@domain.com', 'www.domain.com', '2310456789', 'To be or not to be - that is the question: Whether ''tis nobler in the mind to suffer. The slings and arrows of outrageous fortune, Or to take arms against a sea of troubles. And, by opposing, end them. To die, to sleep. No more - and by a sleep to say we end. The heartache and the thousand natural shocks. That flesh is heir to - tis a consummation. Devoutly to be wished. To die, to sleep. To sleep, perchance to dream. Ay, there''s the rub, For in that sleep of death what dreams may come, When we have shuffled off this mortal coil, Must give us pause. There''s the respect. That makes calamity of so long life. For who would bear the whips and scorns of time, Th’ oppressor''s wrong, the proud man''s contumely, The pangs of despised love, the law''s delay, The insolence of office, and the spurns That patient merit of th’ unworthy takes, When he himself might his quietus make. With a bare bodkin? Who would fardels bear, To grunt and sweat under a weary life, But that the dread of something after death, The undiscovered country from whose bourn. No traveler returns, puzzles the will. And makes us rather bear those ills we have. Than fly to others that we know not of? Thus conscience does make cowards of us all, And thus the native hue of resolution. Is sicklied o''er with the pale cast of thought, And enterprises of great pitch and moment. With this regard their currents turn awry, And lose the name of action. - Soft you now!. The fair Ophelia! Nymph, in thy orisons. Be all my sins remembered.', 6),
(7, 'user@domain.com', 'www.domain.com', '2310456789', 'To be or not to be - that is the question: Whether ''tis nobler in the mind to suffer. The slings and arrows of outrageous fortune, Or to take arms against a sea of troubles. And, by opposing, end them. To die, to sleep. No more - and by a sleep to say we end. The heartache and the thousand natural shocks. That flesh is heir to - tis a consummation. Devoutly to be wished. To die, to sleep. To sleep, perchance to dream. Ay, there''s the rub, For in that sleep of death what dreams may come, When we have shuffled off this mortal coil, Must give us pause. There''s the respect. That makes calamity of so long life. For who would bear the whips and scorns of time, Th’ oppressor''s wrong, the proud man''s contumely, The pangs of despised love, the law''s delay, The insolence of office, and the spurns That patient merit of th’ unworthy takes, When he himself might his quietus make. With a bare bodkin? Who would fardels bear, To grunt and sweat under a weary life, But that the dread of something after death, The undiscovered country from whose bourn. No traveler returns, puzzles the will. And makes us rather bear those ills we have. Than fly to others that we know not of? Thus conscience does make cowards of us all, And thus the native hue of resolution. Is sicklied o''er with the pale cast of thought, And enterprises of great pitch and moment. With this regard their currents turn awry, And lose the name of action. - Soft you now!. The fair Ophelia! Nymph, in thy orisons. Be all my sins remembered.', 7),
(8, 'user@domain.com', 'www.domain.com', '2310456789', 'To be or not to be - that is the question: Whether ''tis nobler in the mind to suffer. The slings and arrows of outrageous fortune, Or to take arms against a sea of troubles. And, by opposing, end them. To die, to sleep. No more - and by a sleep to say we end. The heartache and the thousand natural shocks. That flesh is heir to - tis a consummation. Devoutly to be wished. To die, to sleep. To sleep, perchance to dream. Ay, there''s the rub, For in that sleep of death what dreams may come, When we have shuffled off this mortal coil, Must give us pause. There''s the respect. That makes calamity of so long life. For who would bear the whips and scorns of time, Th’ oppressor''s wrong, the proud man''s contumely, The pangs of despised love, the law''s delay, The insolence of office, and the spurns That patient merit of th’ unworthy takes, When he himself might his quietus make. With a bare bodkin? Who would fardels bear, To grunt and sweat under a weary life, But that the dread of something after death, The undiscovered country from whose bourn. No traveler returns, puzzles the will. And makes us rather bear those ills we have. Than fly to others that we know not of? Thus conscience does make cowards of us all, And thus the native hue of resolution. Is sicklied o''er with the pale cast of thought, And enterprises of great pitch and moment. With this regard their currents turn awry, And lose the name of action. - Soft you now!. The fair Ophelia! Nymph, in thy orisons. Be all my sins remembered.', 8),
(9, 'user@domain.com', 'www.domain.com', '2310456789', 'To be or not to be - that is the question: Whether ''tis nobler in the mind to suffer. The slings and arrows of outrageous fortune, Or to take arms against a sea of troubles. And, by opposing, end them. To die, to sleep. No more - and by a sleep to say we end. The heartache and the thousand natural shocks. That flesh is heir to - tis a consummation. Devoutly to be wished. To die, to sleep. To sleep, perchance to dream. Ay, there''s the rub, For in that sleep of death what dreams may come, When we have shuffled off this mortal coil, Must give us pause. There''s the respect. That makes calamity of so long life. For who would bear the whips and scorns of time, Th’ oppressor''s wrong, the proud man''s contumely, The pangs of despised love, the law''s delay, The insolence of office, and the spurns That patient merit of th’ unworthy takes, When he himself might his quietus make. With a bare bodkin? Who would fardels bear, To grunt and sweat under a weary life, But that the dread of something after death, The undiscovered country from whose bourn. No traveler returns, puzzles the will. And makes us rather bear those ills we have. Than fly to others that we know not of? Thus conscience does make cowards of us all, And thus the native hue of resolution. Is sicklied o''er with the pale cast of thought, And enterprises of great pitch and moment. With this regard their currents turn awry, And lose the name of action. - Soft you now!. The fair Ophelia! Nymph, in thy orisons. Be all my sins remembered.', 9);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;